dist: bionic

sudo: required

language: bash

services:
    - docker

env:
    # PHP 7.2
    - PHP_VERSION=7.2 PSR_HTTP_PROVIDER=nyholm SYMFONY_VERSION=3.4.* XDEBUG_VERSION=2.7.2
    - PHP_VERSION=7.2 PSR_HTTP_PROVIDER=nyholm SYMFONY_VERSION=4.2.* XDEBUG_VERSION=2.7.2
    - PHP_VERSION=7.2 PSR_HTTP_PROVIDER=nyholm SYMFONY_VERSION=4.3.* XDEBUG_VERSION=2.7.2
    - PHP_VERSION=7.2 PSR_HTTP_PROVIDER=nyholm SYMFONY_VERSION=4.4.* XDEBUG_VERSION=2.7.2
    - PHP_VERSION=7.2 PSR_HTTP_PROVIDER=zendframework SYMFONY_VERSION=3.4.* XDEBUG_VERSION=2.7.2
    - PHP_VERSION=7.2 PSR_HTTP_PROVIDER=zendframework SYMFONY_VERSION=4.2.* XDEBUG_VERSION=2.7.2
    - PHP_VERSION=7.2 PSR_HTTP_PROVIDER=zendframework SYMFONY_VERSION=4.3.* XDEBUG_VERSION=2.7.2
    - PHP_VERSION=7.2 PSR_HTTP_PROVIDER=zendframework SYMFONY_VERSION=4.4.* XDEBUG_VERSION=2.7.2

    # PHP 7.3
    - PHP_VERSION=7.3 PSR_HTTP_PROVIDER=nyholm SYMFONY_VERSION=3.4.* XDEBUG_VERSION=2.7.2
    - PHP_VERSION=7.3 PSR_HTTP_PROVIDER=nyholm SYMFONY_VERSION=4.2.* XDEBUG_VERSION=2.7.2
    - PHP_VERSION=7.3 PSR_HTTP_PROVIDER=nyholm SYMFONY_VERSION=4.3.* XDEBUG_VERSION=2.7.2
    - PHP_VERSION=7.3 PSR_HTTP_PROVIDER=nyholm SYMFONY_VERSION=4.4.* XDEBUG_VERSION=2.7.2
    - PHP_VERSION=7.3 PSR_HTTP_PROVIDER=zendframework SYMFONY_VERSION=3.4.* XDEBUG_VERSION=2.7.2
    - PHP_VERSION=7.3 PSR_HTTP_PROVIDER=zendframework SYMFONY_VERSION=4.2.* XDEBUG_VERSION=2.7.2
    - PHP_VERSION=7.3 PSR_HTTP_PROVIDER=zendframework SYMFONY_VERSION=4.3.* XDEBUG_VERSION=2.7.2
    - PHP_VERSION=7.3 PSR_HTTP_PROVIDER=zendframework SYMFONY_VERSION=4.4.* XDEBUG_VERSION=2.7.2

install:
    - dev/bin/docker-compose build --build-arg PHP_VERSION=${PHP_VERSION} --build-arg XDEBUG_VERSION=${XDEBUG_VERSION} php

before_script:
    # Our docker image has symfony/flex installed to make sure SYMFONY_VERSION is working
    - dev/bin/php composer config extra.symfony.require "${SYMFONY_VERSION}"
    - dev/bin/php composer update --ansi --prefer-dist

script:
    - dev/bin/php composer test -- --colors=always --coverage-clover=coverage.xml --debug
    - dev/bin/php composer lint -- --ansi --diff --dry-run --using-cache=no --verbose

after_script:
    - dev/bin/docker-compose down --volumes

after_success:
    - bash <(curl -s https://codecov.io/bash)
